
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-gauchoride-s23-5pm-4
owner: ucsb-cs156-s23
repo_name: proj-gauchoride-s23-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjI5NTg0ODU2","is_bot":false,"login":"strongani","name":"Anikait Mundhra"},"headRefName":"Anikait-rideBackend","number":30,"title":"Anikait Ride Request Backend","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-4/pull/30"},{"author":{"id":"MDQ6VXNlcjQ0NTMwNzM5","is_bot":false,"login":"SophiaWeiler","name":"Sophia Weiler"},"headRefName":"sophia-riderForm","number":28,"title":"Sophia - Adding Rider Request Form","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-4/pull/28"},{"author":{"id":"MDQ6VXNlcjEyNTM2MTg3","is_bot":false,"login":"ameymwalimbe","name":""},"headRefName":"ameymwalimbe-entityDriverShiftTable","number":27,"title":"amey - Add entity file for Driver shift table","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-4/pull/27"},{"author":{"id":"MDQ6VXNlcjEyNzU5Mjg3","is_bot":false,"login":"ru1nw","name":"ian"},"headRefName":"ru1nw-drivertable-frontend","number":26,"title":"driver shift table frontend","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-4/pull/26"},{"author":{"id":"MDQ6VXNlcjcyMjM2OTY4","is_bot":false,"login":"mike-k999","name":""},"headRefName":"Michael-ImproveUserControllerAPIParamDocumentation","number":25,"title":"Michael improve user controller api param documentation","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-4/pull/25"}]
