
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-gauchoride-s23-5pm-4
owner: ucsb-cs156-s23
repo_name: proj-gauchoride-s23-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjcyMjM2OTY4","is_bot":false,"login":"mike-k999","name":""},"headRefName":"Michael-HompageText","number":13,"title":"Michael hompage text","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-4/pull/13"},{"author":{"id":"MDQ6VXNlcjEyNTM2MTg3","is_bot":false,"login":"ameymwalimbe","name":""},"headRefName":"ameymwalimbe-patch-1","number":12,"title":"Update README.md to use our dokku link","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-4/pull/12"}]
